image:
  file: .gitpod.dockerfile
  #context: apache
ports:
- port: 8002
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    ln -s /var/www/hackazon /workspace/apache-example/hackazon && clear
- name: Apache
  command: >
    bash /workspace/apache-example/scripts/start.sh &&
    apachectl start && sleep 10 &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log && clear
