image:
  file: .gitpod.dockerfile
  #context: apache
ports:
- port: 8002
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    bash /workspace/apache-example/scripts/start.sh &&
    apachectl start && sleep 10 &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log && clear
